#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: gradle:6.6.0

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          script:
            - gradle build unpackDist
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t observer/$BITBUCKET_BUILD_NUMBER
            - docker push observer/$BITBUCKET_BUILD_NUMBER
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
          services:
            - docker
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
